services:
  backend:
    build: .
    ports:
      - '3030:8080'
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./static:/app/static
    restart: unless-stopped
