version: '3.8'

services:
  backend:
    build: .
    ports:
      - '3030:8080'
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - ./static:/app/static
      - ./distStatic:/app/dist/static
    restart: unless-stopped
